// <auto-generated />
using System;
using HR.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HR.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HrDbContext))]
    [Migration("20260803085102_AddAuth")]
    partial class AddAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HR.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique();

                    b.ToTable("AttendanceRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            CheckInTime = new TimeOnly(8, 57, 0),
                            CheckOutTime = new TimeOnly(17, 8, 0),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Status = "Present",
                            WorkDate = new DateOnly(2026, 7, 28)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            CheckInTime = new TimeOnly(9, 24, 0),
                            CheckOutTime = new TimeOnly(17, 3, 0),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000006"),
                            Notes = "Needs HR review",
                            Status = "Late",
                            WorkDate = new DateOnly(2026, 7, 28)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            CheckInTime = new TimeOnly(9, 5, 0),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Notes = "Auto reminder queued",
                            Status = "MissingCheckout",
                            WorkDate = new DateOnly(2026, 7, 28)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            CheckInTime = new TimeOnly(9, 0, 0),
                            CheckOutTime = new TimeOnly(17, 0, 0),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Notes = "Remote today",
                            Status = "Remote",
                            WorkDate = new DateOnly(2026, 7, 28)
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000009"),
                            Notes = "Time off, back Aug 31, 2026",
                            Status = "Absent",
                            WorkDate = new DateOnly(2026, 7, 28)
                        });
                });

            modelBuilder.Entity("HR.Domain.Auth.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("[EmployeeId] IS NOT NULL");

                    b.ToTable("AppUsers", (string)null);
                });

            modelBuilder.Entity("HR.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("HR.Domain.Contracts.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "EndDate");

                    b.ToTable("Contracts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000005"),
                            EndDate = new DateOnly(2027, 5, 31),
                            StartDate = new DateOnly(2025, 5, 31),
                            Status = "Active",
                            Type = "FullTime"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000006"),
                            EndDate = new DateOnly(2026, 11, 18),
                            StartDate = new DateOnly(2025, 11, 18),
                            Status = "Active",
                            Type = "FullTime"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000007"),
                            EndDate = new DateOnly(2026, 8, 14),
                            Notes = "Contract ends soon",
                            StartDate = new DateOnly(2025, 8, 14),
                            Status = "ReviewRequired",
                            Type = "FullTime"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000008"),
                            EndDate = new DateOnly(2027, 1, 10),
                            StartDate = new DateOnly(2026, 1, 10),
                            Status = "Active",
                            Type = "FullTime"
                        });
                });

            modelBuilder.Entity("HR.Domain.Employees.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "HR",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HR"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "PRODUCT",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Product"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "SALES",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sales"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "DELIVERY",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Delivery"
                        });
                });

            modelBuilder.Entity("HR.Domain.Employees.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "rawan.elkhodary@hrsystem.local",
                            EmployeeNumber = "EMP-1001",
                            FirstName = "Rawan",
                            HireDate = new DateOnly(2024, 1, 15),
                            JobTitle = "Product Designer",
                            LastName = "ElKhodary",
                            Location = "Cairo",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Email = "rana.youssef@hrsystem.local",
                            EmployeeNumber = "EMP-1010",
                            FirstName = "Rana",
                            HireDate = new DateOnly(2022, 3, 1),
                            JobTitle = "HR Manager",
                            LastName = "Youssef",
                            Location = "Cairo",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "karim.adel@hrsystem.local",
                            EmployeeNumber = "EMP-1020",
                            FirstName = "Karim",
                            HireDate = new DateOnly(2021, 11, 7),
                            JobTitle = "Product Manager",
                            LastName = "Adel",
                            Location = "Cairo",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Email = "lina.maher@hrsystem.local",
                            EmployeeNumber = "EMP-1030",
                            FirstName = "Lina",
                            HireDate = new DateOnly(2021, 6, 14),
                            JobTitle = "Sales Manager",
                            LastName = "Maher",
                            Location = "Dubai",
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Email = "nour.hassan@hrsystem.local",
                            EmployeeNumber = "EMP-1042",
                            FirstName = "Nour",
                            HireDate = new DateOnly(2023, 2, 5),
                            JobTitle = "People Operations Lead",
                            LastName = "Hassan",
                            Location = "Cairo",
                            ManagerId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "omar.nabil@hrsystem.local",
                            EmployeeNumber = "EMP-1087",
                            FirstName = "Omar",
                            HireDate = new DateOnly(2024, 4, 8),
                            JobTitle = "Frontend Engineer",
                            LastName = "Nabil",
                            Location = "Alexandria",
                            ManagerId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Status = "Active"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Email = "mariam.samir@hrsystem.local",
                            EmployeeNumber = "EMP-1120",
                            FirstName = "Mariam",
                            HireDate = new DateOnly(2023, 8, 14),
                            JobTitle = "Account Executive",
                            LastName = "Samir",
                            Location = "Dubai",
                            ManagerId = new Guid("20000000-0000-0000-0000-000000000004"),
                            Status = "ContractReview"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000004"),
                            Email = "youssef.galal@hrsystem.local",
                            EmployeeNumber = "EMP-1184",
                            FirstName = "Youssef",
                            HireDate = new DateOnly(2026, 4, 1),
                            JobTitle = "QA Analyst",
                            LastName = "Galal",
                            Location = "Remote",
                            ManagerId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Status = "Probation"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "ahmed.mohamed@hrsystem.local",
                            EmployeeNumber = "EMP-1190",
                            FirstName = "Ahmed",
                            HireDate = new DateOnly(2024, 9, 9),
                            JobTitle = "Backend Engineer",
                            LastName = "Mohamed",
                            Location = "Cairo",
                            ManagerId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("HR.Domain.Leave.LeaveBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EntitledDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PendingDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UsedDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("EmployeeId", "LeaveTypeId", "Year")
                        .IsUnique();

                    b.ToTable("LeaveBalances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntitledDays = 8.5m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PendingDays = 0m,
                            UsedDays = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntitledDays = 3m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000002"),
                            PendingDays = 0m,
                            UsedDays = 1m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntitledDays = 5m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000003"),
                            PendingDays = 0m,
                            UsedDays = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntitledDays = 3m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000004"),
                            PendingDays = 0m,
                            UsedDays = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntitledDays = 3m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000005"),
                            PendingDays = 0m,
                            UsedDays = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000001"),
                            EntitledDays = 5m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000006"),
                            PendingDays = 0m,
                            UsedDays = 0m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000005"),
                            EntitledDays = 21m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PendingDays = 0m,
                            UsedDays = 8m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000008"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000006"),
                            EntitledDays = 21m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PendingDays = 4m,
                            UsedDays = 14m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000009"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000007"),
                            EntitledDays = 21m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PendingDays = 0m,
                            UsedDays = 17m,
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000010"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000008"),
                            EntitledDays = 15m,
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            PendingDays = 0m,
                            UsedDays = 3m,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("HR.Domain.Leave.LeaveRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeaveTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RequestedDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReviewedByEmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("ReviewedByEmployeeId");

                    b.ToTable("LeaveRequests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000006"),
                            EndDate = new DateOnly(2026, 8, 7),
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000001"),
                            Reason = "Annual leave",
                            RequestedAtUtc = new DateTime(2026, 7, 28, 8, 30, 0, 0, DateTimeKind.Utc),
                            RequestedDays = 4m,
                            StartDate = new DateOnly(2026, 8, 4),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000007"),
                            EndDate = new DateOnly(2026, 7, 30),
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000005"),
                            Reason = "Emergency leave",
                            RequestedAtUtc = new DateTime(2026, 7, 28, 9, 15, 0, 0, DateTimeKind.Utc),
                            RequestedDays = 1m,
                            StartDate = new DateOnly(2026, 7, 30),
                            Status = "Pending"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            EmployeeId = new Guid("20000000-0000-0000-0000-000000000008"),
                            EndDate = new DateOnly(2026, 7, 28),
                            LeaveTypeId = new Guid("30000000-0000-0000-0000-000000000002"),
                            Reason = "Sick leave",
                            RequestedAtUtc = new DateTime(2026, 7, 27, 7, 0, 0, 0, DateTimeKind.Utc),
                            RequestedDays = 1m,
                            ReviewedAtUtc = new DateTime(2026, 7, 27, 11, 45, 0, 0, DateTimeKind.Utc),
                            ReviewedByEmployeeId = new Guid("20000000-0000-0000-0000-000000000005"),
                            StartDate = new DateOnly(2026, 7, 28),
                            Status = "Approved"
                        });
                });

            modelBuilder.Entity("HR.Domain.Leave.LeaveType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AnnualAllowanceDays")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("LeaveTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AnnualAllowanceDays = 21m,
                            Code = "ANNUAL",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true,
                            Name = "Annual Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AnnualAllowanceDays = 10m,
                            Code = "SICK",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true,
                            Name = "Sick Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AnnualAllowanceDays = 5m,
                            Code = "CASUAL",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true,
                            Name = "Casual Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AnnualAllowanceDays = 3m,
                            Code = "COMPASSIONATE",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true,
                            Name = "Compassionate Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AnnualAllowanceDays = 3m,
                            Code = "EMERGENCY",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true,
                            Name = "Emergency Leave",
                            RequiresApproval = true
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000006"),
                            AnnualAllowanceDays = 5m,
                            Code = "MARRIAGE",
                            CreatedAtUtc = new DateTime(2026, 7, 28, 9, 0, 0, 0, DateTimeKind.Utc),
                            IsPaid = true,
                            Name = "Marriage Leave",
                            RequiresApproval = true
                        });
                });

            modelBuilder.Entity("HR.Domain.Attendance.AttendanceRecord", b =>
                {
                    b.HasOne("HR.Domain.Employees.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR.Domain.Auth.AppUser", b =>
                {
                    b.HasOne("HR.Domain.Employees.Employee", "Employee")
                        .WithOne()
                        .HasForeignKey("HR.Domain.Auth.AppUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("HR.Domain.Auth.AppUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HR.Domain.Contracts.Contract", b =>
                {
                    b.HasOne("HR.Domain.Employees.Employee", "Employee")
                        .WithMany("Contracts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HR.Domain.Employees.Employee", b =>
                {
                    b.HasOne("HR.Domain.Employees.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Employees.Employee", "Manager")
                        .WithMany("DirectReports")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("HR.Domain.Leave.LeaveBalance", b =>
                {
                    b.HasOne("HR.Domain.Employees.Employee", "Employee")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Leave.LeaveType", "LeaveType")
                        .WithMany("LeaveBalances")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("HR.Domain.Leave.LeaveRequest", b =>
                {
                    b.HasOne("HR.Domain.Employees.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HR.Domain.Leave.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HR.Domain.Employees.Employee", "ReviewedByEmployee")
                        .WithMany()
                        .HasForeignKey("ReviewedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Employee");

                    b.Navigation("LeaveType");

                    b.Navigation("ReviewedByEmployee");
                });

            modelBuilder.Entity("HR.Domain.Auth.AppUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("HR.Domain.Employees.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HR.Domain.Employees.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Contracts");

                    b.Navigation("DirectReports");

                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("HR.Domain.Leave.LeaveType", b =>
                {
                    b.Navigation("LeaveBalances");

                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
